const data = {
  books: [
    {
      id: 1,
      title: "To Kill a Mockingbird",
      author: {
        id: 1,
        name: "Harper Lee",
        birth_year: 1926,
      },
      genre: "Fiction",
      published_year: 1960,
      isbn: "9780061120084",
    },
    {
      id: 2,
      title: "1984",
      author: {
        id: 2,
        name: "George Orwell",
        birth_year: 1903,
      },
      genre: "Dystopian Fiction",
      published_year: 1949,
      isbn: "9780451524935",
    },
    {
      id: 3,
      title: "The Great Gatsby",
      author: {
        id: 3,
        name: "F. Scott Fitzgerald",
        birth_year: 1896,
      },
      genre: "Fiction",
      published_year: 1925,
      isbn: "9780743273565",
    },
    {
      id: 4,
      title: "Pride and Prejudice",
      author: {
        id: 4,
        name: "Jane Austen",
        birth_year: 1775,
      },
      genre: "Romantic Fiction",
      published_year: 1813,
      isbn: "9780141439518",
    },
    {
      id: 5,
      title: "The Catcher in the Rye",
      author: {
        id: 5,
        name: "J.D. Salinger",
        birth_year: 1919,
      },
      genre: "Fiction",
      published_year: 1951,
      isbn: "9780316769488",
    },
    {
      id: 6,
      title: "Moby-Dick",
      author: {
        id: 6,
        name: "Herman Melville",
        birth_year: 1819,
      },
      genre: "Adventure Fiction",
      published_year: 1851,
      isbn: "9781503280785",
    },
    {
      id: 7,
      title: "The Lord of the Rings",
      author: {
        id: 7,
        name: "J.R.R. Tolkien",
        birth_year: 1892,
      },
      genre: "Fantasy",
      published_year: 1954,
      isbn: "9780618640157",
    },
    {
      id: 8,
      title: "Frankenstein",
      author: {
        id: 8,
        name: "Mary Shelley",
        birth_year: 1797,
      },
      genre: "Gothic Fiction",
      published_year: 1818,
      isbn: "9780486282114",
    },
    {
      id: 9,
      title: "The Hobbit",
      author: {
        id: 7,
        name: "J.R.R. Tolkien",
        birth_year: 1892,
      },
      genre: "Fantasy",
      published_year: 1937,
      isbn: "9780618260300",
    },
    {
      id: 10,
      title: "Wuthering Heights",
      author: {
        id: 9,
        name: "Emily Brontë",
        birth_year: 1818,
      },
      genre: "Gothic Fiction",
      published_year: 1847,
      isbn: "9780553212587",
    },
    {
      id: 11,
      title: "The Picture of Dorian Gray",
      author: {
        id: 10,
        name: "Oscar Wilde",
        birth_year: 1854,
      },
      genre: "Gothic Fiction",
      published_year: 1890,
      isbn: "9780141439570",
    },
    {
      id: 12,
      title: "Brave New World",
      author: {
        id: 11,
        name: "Aldous Huxley",
        birth_year: 1894,
      },
      genre: "Science Fiction",
      published_year: 1932,
      isbn: "9780060850524",
    },
    {
      id: 13,
      title: "Alice's Adventures in Wonderland",
      author: {
        id: 12,
        name: "Lewis Carroll",
        birth_year: 1832,
      },
      genre: "Fantasy",
      published_year: 1865,
      isbn: "9780141439761",
    },
    {
      id: 14,
      title: "The Little Prince",
      author: {
        id: 13,
        name: "Antoine de Saint-Exupéry",
        birth_year: 1900,
      },
      genre: "Children's Literature",
      published_year: 1943,
      isbn: "9780156012195",
    },
    {
      id: 15,
      title: "Dracula",
      author: {
        id: 14,
        name: "Bram Stoker",
        birth_year: 1847,
      },
      genre: "Gothic Fiction",
      published_year: 1897,
      isbn: "9780486411095",
    },
    {
      id: 16,
      title: "The Odyssey",
      author: {
        id: 15,
        name: "Homer",
        birth_year: "Unknown",
      },
      genre: "Epic Poetry",
      published_year: "8th Century BC",
      isbn: "9780140449112",
    },
    {
      id: 17,
      title: "Fahrenheit 451",
      author: {
        id: 2,
        name: "Ray Bradbury",
        birth_year: 1920,
      },
      genre: "Dystopian Fiction",
      published_year: 1953,
      isbn: "9781451673319",
    },
    {
      id: 18,
      title: "Slaughterhouse-Five",
      author: {
        id: 16,
        name: "Kurt Vonnegut",
        birth_year: 1922,
      },
      genre: "Science Fiction",
      published_year: 1969,
      isbn: "9780385333849",
    },
    {
      id: 19,
      title: "The Grapes of Wrath",
      author: {
        id: 17,
        name: "John Steinbeck",
        birth_year: 1902,
      },
      genre: "Historical Fiction",
      published_year: 1939,
      isbn: "9780143039433",
    },
    {
      id: 20,
      title: "The Alchemist",
      author: {
        id: 18,
        name: "Paulo Coelho",
        birth_year: 1947,
      },
      genre: "Philosophical Fiction",
      published_year: 1988,
      isbn: "9780062315007",
    },
  ],
};
